CREATE DATABASE VB;
CREATE TABLE PROJECT(
ID INT PRIMARY KEY,
STU_NAME  VARCHAR(23),
STU_COURSE VARCHAR(23),
);

insert into PROJECT values(1001,'PEH ATTA JOSEPH','Bsc Computer Science');
insert into PROJECT values(1002,'BELINDA TANOR','Bsc Computer Science');
insert into PROJECT values(1003,'YAA BERNICE','MEDICINE');
insert into PROJECT values(1004,'JAME BONFE','IT');
insert into PROJECT values(1005,'JOANA ','ECONOMIC Science');
insert into PROJECT values(1006,'AMPOFO','Bsc Computer Science');
insert into PROJECT values('AMPOFO','Bsc Computer Science');
SELECT * from PROJECT;
update project set
STU_COURSE='CHEMISTRY'
where STU_NAME='JOANA'

/*ADDING CONTRAINTS*/
/*null/not null*/
     ALTER TABLE PROJECT  ALTER COLUMN  STU_NAME VARCHAR(23) NOT NULL;
	   ALTER TABLE PROJECT  ALTER COLUMN  STU_NAME VARCHAR(23)   NULL;

	   /*default*/
	   CREATE TABLE def(
ID INT PRIMARY KEY,
STU_NAME  VARCHAR(23),
STU_COURSE VARCHAR(23) DEFAULT 'BSC COMPUTER SCIENCE',
JOINDATE DATETIME DEFAULT Getdate(),

);



insert into def(ID,STU_NAME) values(1004,'BELINDA TANOR');
/*NB YOU HAVE TO SPECIFY THE COLUMN LENTH BEFORE IT RECIEVE ONLY A CERTAIN NUMBER OF INPUT*/
insert into PROJECT values(1003,'YAA BERNICE','MEDICINE');
insert into PROJECT values(1004,'JAME BONFE','IT');
insert into PROJECT values(1005,'JOANA ','ECONOMIC Science');
insert into PROJECT values(1006,'AMPOFO','Bsc Computer Science');

SELECT * FROM DEF
/*applyin default after the table has been created and droping as well*/
ALTER TABLE DEF ADD CONSTRAINT STU_NAME default 'BERNICE' FOR STU_NAME;
ALTER TABLE DEF DROP CONSTRAINT STU_NAME
insert into def(ID) values(1006);

/*UNIQUE*/
  CREATE TABLE UN(
ID INT NOT NULL UNIQUE,
STU_NAME  VARCHAR(23) NOT NULL,
STU_COURSE VARCHAR(23)  NOT NULL,
AGE INT,
EMAIL VARCHAR(34),

);

insert into UN(ID,STU_NAME,STU_COURSE,AGE) values(1005,'JOANA ','ECONOMIC Science',17);
insert into UN(ID,STU_NAME,STU_COURSE,AGE) values(1004,'BERNICE ','Computer Science',16);
select * from	UN
/*ADDING CONSTRAINT AFTER THE TABLE HAS BEEN CREATED AND DROPING*/
ALTER TABLE UN ADD CONSTRAINT SPECIFY_NAME UNIQUE(ID,STU_NAME,EMAIL);

ALTER TABLE UN DROP CONSTRAINT SPECIFY_NAME;
/*PRIMARY KEY*/


  CREATE TABLE PRIM(
ID INT NOT NULL PRIMARY KEY,
STU_NAME  VARCHAR(23) NOT NULL,
STU_COURSE VARCHAR(23)  NOT NULL,
AGE INT,
EMAIL VARCHAR(34),

);
insert into PRIM(ID,STU_NAME,STU_COURSE,AGE) values(1005,'JOANA ','ECONOMIC Science',17);
insert into PRIM(ID,STU_NAME,STU_COURSE,AGE) values(1005,'BERNICE ','Computer Science',16);

SELECT * FROM PRIM
/*ADDING CONSTRAINT AFTER THE TABLE HAS BEEN CREATED AND DROPING*/
 CREATE TABLE PRIM1(
ID INT NOT NULL ,
STU_NAME  VARCHAR(23) NOT NULL,
STU_COURSE VARCHAR(23)  NOT NULL,
AGE INT,
EMAIL VARCHAR(34),

);
ALTER TABLE PRIM1 ADD CONSTRAINT PRIMKEY primary key(ISTU_COURSE);
ALTER TABLE PRIM1 DROP CONSTRAINT PRIMKEY;

/*FOREIGN KEY*/
CREATE TABLE FK(
ID INT PRIMARY KEY NOT NULL ,
STU_NAME  VARCHAR(23) NOT NULL,
STU_COURSE VARCHAR(23)  NOT NULL,
AGE INT,
EMAIL VARCHAR(34),

);
CREATE TABLE FK2(
ID INT NOT NULL REFERENCES FK(ID) ,
STU_NAME  VARCHAR(23) NOT NULL,
STU_COURSE VARCHAR(23)  NOT NULL,
AGE INT,
EMAIL VARCHAR(34),

);
insert into fk(ID,STU_NAME,STU_COURSE,AGE) values(1005,'JOANA ','ECONOMIC Science',17);
insert into fk2(ID,STU_NAME,STU_COURSE,AGE) values(1005,'BERNICE ','Computer Science',16);
insert into fk(ID,STU_NAME,STU_COURSE,AGE) values(1009,'JOANA ','ECONOMIC Science',17);
insert into fk2(ID,STU_NAME,STU_COURSE,AGE) values(1009,'BERNICE ','Computer Science',16);


SELECT * FROM FK

INNER JOIN  FK2
ON
 FK.ID = FK2.ID
 /*ADDING CONSTRAINT AFTER THE TABLE HAS BEEN CREATED AND DROPING*/
 /*for the foreign key to work perfectely you have to set a primary key 
 on the references table and also a primary key in the table of the foreign key that matches*/
ALTER TABLE FK2 ADD CONSTRAINT PEHJOS FOREIGN KEY(STU_COURSE)references FK(STU_COURSE);
ALTER TABLE FK2 drop CONSTRAINT PEHJOS


SELECT * FROM FK2


/*CHECK*/
CREATE TABLE CK(
ID INT NOT NULL REFERENCES FK(ID) ,
STU_NAME  VARCHAR(23) NOT NULL,
STU_COURSE VARCHAR(23)  NOT NULL,
AGE INT CHECK(AGE>23),
EMAIL VARCHAR(34),

);
insert into CK(ID,STU_NAME,STU_COURSE,AGE) values(1006,'BERNICE ','Computer ',13);
SELECT * FROM CK

 /*ADDING CONSTRAINT AFTER THE TABLE HAS BEEN CREATED AND DROPING*/
 alter table ck add constraint peh check(stu_course='computer science' );
 alter table ck drop constraint peh



 /*ALL RIGHT RESERVED PEHJOS 2020*/